import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import styled from "styled-components";
import Link,{LinkProps} from "next/link";

type BaseLinkProps = React.PropsWithChildren<LinkProps> & {
  className?:string,
  children:React.ReactNode
}

const BaseLink = (props:BaseLinkProps) =>{
  const {className,children,...rest} = props;
  return (
    <Link {...rest}>
      <a className={className}>{children}</a>
    </Link>
  )
}

const StyledLink = styled(BaseLink)`
color:#1e90ff;
font-size:2em;
`


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <StyledLink href="/">
      Goooooo!!!
    </StyledLink>

    </div>
  )
}

export default Home
